### ISSUE TITLE
TypeError: sequence index must be integer, not 'str'

### ISSUE THREAD

**Issue by fabiomfpinto** [a-moss/PoGoAccountCheck#2]
I am getting this error. Any tip or I did something wrong? thank you :)

Traceback (most recent call last):
  File "banned.py", line 44, in <module>
    check_account(username, password)
  File "banned.py", line 26, in check_account
    if response['status_code'] == 3:
TypeError: sequence index must be integer, not 'str'

**Comment by a-moss** [comment]
Hm.. are you able to reproduce this bug? Or was it a one-time thing?

Also, just to double check, make sure you have ran this command from within the directory: pip install -r requirements.txt

**Comment by EiTeR94** [comment]
same error

**Comment by EiTeR94** [comment]
well, ok, i can say you how to fix it.

fabiomfpinto and i, are trting to test a google account.
Your banned.py is only for PTC account.
So you have to put a if at line 21 to check if it's PTC account ( just the username ) or if it's a google account ( mail adress ).

Or fabiomfpinto, you have to open banned.py and change this line 21: 

api.login('ptc', username, password)

by : 

api.login('google', username, password)

**Comment by a-moss** [comment]
Ah, forgot about Google accounts. I'll make a commit for this later today. Thanks for figuring it out!

**Comment by engle2192** [comment]
Im still getting this error and im trying to use PTC accounts.

Traceback (most recent call last):
  File "banned.py", line 44, in <module>
    check_account(username, password)
  File "banned.py", line 26, in check_account
    if response['status_code'] == 3:
TypeError: sequence index must be integer, not 'str'

**Comment by fabiomfpinto** [comment]
Well I didn't time yet to test but maybe I know the problem ... In txt file I used all accounts in collumn and not in a row... I will try that way and wioo give some feedback. Anyway I installed all requirements correctly ... Thank you for your responses guys

**Comment by fabiomfpinto** [comment]
I think i already know te problem. I tested with some accounts (ptc) without capital letters and short usernames and it worked everything like it should. So maybe the problem is the variable it cant "save" the things inside because str (string) doesnt suppport it. I already tried with integer, long and the other therms and same error all the time :(

**Comment by w0nnapl4y** [comment]
This happens as soon as you put in an account that doesn't exist (anymore).
The script crashes at the first non-existent username.

**Comment by fabiomfpinto** [comment]
yup @w0nnapl4y you have reason! i checked the account and doesnt exist anymore. They deleted these accounts maybe lol

**Comment by a-moss** [comment]
Hmm interesting. I wonder if they eventually delete banned accounts. I'll push a commit later today to fix it.

**Comment by w0nnapl4y** [comment]
I can confirm that some accounts which have been scanners are now deleted.

**Comment by engle2192** [comment]
After latest commit still getting

Traceback (most recent call last):
  File "banned.py", line 48, in <module>
    check_account(username, password)
  File "banned.py", line 30, in check_account
    if response['status_code'] == 3:
TypeError: sequence index must be integer, not 'str'

**Comment by a-moss** [comment]
Whoops - I must have missed something. The patch only fixed it for google accounts. I'll fix it when I get home again for PTC accounts.

**Comment by a-moss** [comment]
@engle2192 

Ok, latest commit should actually fix this issue. If you could double check that it works on your end, that would be great.

**Comment by engle2192** [comment]
@a-moss 

Its good now! Thanks!

**Comment by a-moss** [comment]
Awesome, closing this issue then.
