### ISSUE TITLE
Suggestion: hard coded location for login

### ISSUE THREAD

**Issue by edevnull** [a-moss/PoGoAccountCheck#3]
The GPS cords passed to the login are hard coded to (40.7127837, -74.005941, 0.0)

Might be good to add the -l flag like PokemonGo-Map where it can be provided.

**Comment by a-moss** [comment]
I can see why this may be useful. I'll see if I can make a commit later today to implement this.

**Comment by a-moss** [comment]
Added.

You can use this by utilizing the -l argument. Supply coordinates like you would with PokemonGo-Map where there is a space in between.

ie: python banned.py -f accounts.txt -l '40.7127837 -74.005941'
